"""
Discrete-event NTN simulator with queues, key pools, and Age-of-Secret
routing.  Companion to Paper 2 (MILCOM 2026, sole author Liang Dong).

The simulator runs in 1-second steps.  Each step:

  1. Refresh classical link availability from the Walker constellation
     pass-window schedule.
  2. Inject classical capacity / latency for available edges.
  3. Generate keys on QKD-capable edges with currently-available passes.
  4. Inject traffic arrivals at flow sources.
  5. Compute per-link routing/scheduling decision under the active
     algorithm (AoS-backpressure or one of four baselines).
  6. Drain queues + consume keys for served packets.
  7. Log per-step state for offline analysis.

The schedulers compared:

  * shortest_path    - static lowest-hop route, PQC-only key supply.
  * max_throughput   - static lowest-latency route, PQC-only key supply.
  * pqc_only         - shortest-path, refuses any QKD use even when present.
  * qkd_only         - prefers QKD-capable edges; refuses PQC fallback.
  * key_rate_aware   - greedy on per-link key inflow rate.
  * aos_backpressure - AoS-aware backpressure (this paper).

Author: Liang Dong, MILCOM 2026 Paper 2.
"""

from __future__ import annotations

import argparse
import csv
import dataclasses
import json
import math
import random
import time
from collections import defaultdict, deque
from itertools import combinations
from pathlib import Path
from typing import Iterable

import numpy as np

from constellation import (
    DEFAULT_GROUND_STATIONS, DEFAULT_SHELL, GroundStation,
    build_satellites, cloud_transmittance, load_real_or_synthetic,
    make_walker_tles, passes, qkd_rate_bps,
)
from skyfield.api import load


# ---------------------------------------------------------------------------
# Network topology
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class Edge:
    src: str
    dst: str
    capacity_bps: float        # classical link capacity
    latency_ms: float          # classical end-to-end propagation
    qkd_capable: bool = False  # whether QKD can generate keys on this link
    k_min_bits: float = 50_000        # policy reserve (50 kb default)
    k_max_bits: float = 5_000_000     # cap (5 Mb default)
    pqc_refresh_bps: float = 200_000  # PQC refresh: ~ML-KEM throughput on 1 core

    def key(self) -> tuple[str, str]:
        return (self.src, self.dst)


# 1 session-key bit covers this many protected payload bits (AES-256
# rekeyed once per 256 packets ~ 32 bytes key per 256*1500 B = 384000 B).
KEY_BITS_PER_PAYLOAD_BIT = 1.0 / 256.0


def default_topology() -> tuple[list[str], list[Edge]]:
    """Tactical-edge NTN topology, classical data plane only.

    Nodes: six ground stations + four regional gateways.  All edges are
    classical and carry packets.  QKD is a *key-supply overlay* attached
    to ground stations: keys generated by Walker-Delta passes refresh
    the GS-incident edges' key pools (see `qkd_capable=True` flag) but
    QKD is not a routing hop.
    """
    gs_names = [g.name for g in DEFAULT_GROUND_STATIONS]
    gw_names = ["GW-NAEast", "GW-NAWest", "GW-EU", "GW-APAC"]
    nodes = gs_names + gw_names

    edges: list[Edge] = []
    # Terrestrial gateway-mesh (high capacity, low latency)
    gw_pairs = list(combinations(gw_names, 2))
    for a, b in gw_pairs:
        edges.append(Edge(a, b, capacity_bps=10e9, latency_ms=45.0))
        edges.append(Edge(b, a, capacity_bps=10e9, latency_ms=45.0))

    # Each GS is multi-homed: one primary gateway (low latency) and a
    # secondary one (higher latency) for routing diversity.  Both edges
    # receive QKD refresh from the GS's overhead passes.
    gs_attach = {
        "Waco-TX":        [("GW-NAWest", 20.0), ("GW-NAEast", 40.0)],
        "FortBragg-NC":   [("GW-NAEast", 18.0), ("GW-NAWest", 42.0)],
        "RamsteinAB-DE":  [("GW-EU",     16.0), ("GW-NAEast", 80.0)],
        "Yokota-JP":      [("GW-APAC",   22.0), ("GW-NAWest", 90.0)],
        "Diego-Garcia":   [("GW-APAC",   30.0), ("GW-EU",     70.0)],
        "CampLemonnier":  [("GW-EU",     26.0), ("GW-APAC",   85.0)],
    }
    for gs, attachments in gs_attach.items():
        for gw, latency in attachments:
            edges.append(Edge(gs, gw, capacity_bps=1e9, latency_ms=latency,
                              qkd_capable=True))
            edges.append(Edge(gw, gs, capacity_bps=1e9, latency_ms=latency,
                              qkd_capable=True))

    return nodes, edges


# ---------------------------------------------------------------------------
# Flow definition
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class Flow:
    name: str
    src: str
    dst: str
    arrival_bps: float                # mean classical-payload arrival
    security_class: str = "session"   # session / command / bulk
    aos_max: float = 60.0             # seconds: freshness target
    key_bits_per_packet: float = 256  # AES-256 session-key cost per packet


def default_flows() -> list[Flow]:
    return [
        Flow("cmd-A", "Waco-TX",       "RamsteinAB-DE", 30e6, "command", aos_max=20),
        Flow("cmd-B", "FortBragg-NC",  "Yokota-JP",     25e6, "command", aos_max=20),
        Flow("ses-A", "RamsteinAB-DE", "Diego-Garcia",  50e6, "session", aos_max=60),
        Flow("ses-B", "Yokota-JP",     "Waco-TX",       40e6, "session", aos_max=60),
        Flow("bulk-A","CampLemonnier", "FortBragg-NC", 100e6, "bulk",    aos_max=120),
    ]


# ---------------------------------------------------------------------------
# Pre-computed pass-window schedule
# ---------------------------------------------------------------------------

def build_qkd_schedule(start_jd: float, hours: float = 12.0,
                       min_elev_deg: float = 25.0,
                       max_sats: int | None = None,
                       weather_seed: int = 0,
                       prefer_real: bool = True
                       ) -> tuple[dict, str]:
    """Return ``(schedule, provenance)``.

    ``schedule`` is a per-ground-station list of
    ``(t_start, t_end, peak_elev, average-rate-bps)`` tuples spanning the
    requested window.  ``provenance`` is a short string describing whether
    the underlying constellation came from a real TLE snapshot or the
    synthetic Walker-Delta fallback.

    For each pass we draw a single weather factor in [0.4, 1.0] to model
    cloud/optical-attenuation effects.  This is the legacy weather model;
    see ``itu_p840`` for the physics-based model used in the experiments.
    """
    rng = np.random.default_rng(weather_seed)
    tles, provenance = load_real_or_synthetic(prefer_real=prefer_real)
    if max_sats is not None:
        tles = tles[:max_sats]
    sats = build_satellites(tles)
    ts = load.timescale()
    t_start = ts.tt_jd(start_jd)
    t_end   = ts.tt_jd(start_jd + hours / 24.0)
    sched = {g.name: [] for g in DEFAULT_GROUND_STATIONS}
    for sat in sats:
        for gs in DEFAULT_GROUND_STATIONS:
            for rise_tt, set_tt, peak_elev in passes(sat, gs, t_start, t_end,
                                                     min_elev_deg=min_elev_deg):
                # Physics-based cloud transmittance (see constellation.py)
                weather = cloud_transmittance(peak_elev, rng=rng)
                avg_rate = qkd_rate_bps(peak_elev, weather=weather) * 0.6
                t0_s = (rise_tt - start_jd) * 86400.0
                t1_s = (set_tt  - start_jd) * 86400.0
                if t1_s > t0_s:
                    sched[gs.name].append((t0_s, t1_s, peak_elev, avg_rate))
    for gs in sched:
        sched[gs].sort()
    return sched, provenance


def qkd_rate_at(t_s: float, schedule_for_gs: list[tuple]) -> float:
    """Return aggregate QKD generation rate (bps) at simulation time t_s."""
    r = 0.0
    for t0, t1, _, rate in schedule_for_gs:
        if t0 <= t_s <= t1:
            r += rate
    return r


# ---------------------------------------------------------------------------
# Network simulator
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class SimConfig:
    horizon_s: int = 600
    dt_s: int = 1
    seed: int = 0
    pqc_handshake_bits: float = 8192    # cost of one ML-KEM handshake
    aos_lambda: float = 2.0             # AoS depletion-risk weight
    aos_mu: float = 0.5                 # AoS trust-risk weight
    bp_alpha: float = 5.0e-7            # backpressure key-gradient weight
    bp_beta: float = 1.0e-3             # backpressure latency penalty
    bp_chi: float = 5.0e-3              # backpressure AoS penalty
    bp_omega: float = 2.0e2             # Lyapunov Z weight in ideal max-weight
    scheduler: str = "aos_backpressure"
    scenario: str = "nominal"


def neighbours(edges: list[Edge]) -> dict[str, list[Edge]]:
    out = defaultdict(list)
    for e in edges:
        out[e.src].append(e)
    return out


def shortest_paths(nodes: list[str], edges: list[Edge],
                   metric: str = "hops") -> dict:
    """Single-source shortest paths from every node, by chosen metric."""
    nbr = neighbours(edges)
    sps = {}
    for s in nodes:
        dist = {n: math.inf for n in nodes}
        prev = {n: None for n in nodes}
        dist[s] = 0
        unvisited = set(nodes)
        while unvisited:
            u = min(unvisited, key=lambda x: dist[x])
            if dist[u] == math.inf:
                break
            unvisited.remove(u)
            for e in nbr.get(u, []):
                w = 1 if metric == "hops" else e.latency_ms
                d = dist[u] + w
                if d < dist[e.dst]:
                    dist[e.dst] = d
                    prev[e.dst] = u
        sps[s] = prev
    return sps


def path(prev: dict, src: str, dst: str) -> list[str]:
    out = []
    cur = dst
    while cur is not None:
        out.append(cur)
        if cur == src:
            break
        cur = prev[cur]
    return list(reversed(out)) if out and out[-1] == src else []


@dataclasses.dataclass
class StepLog:
    t: int
    total_secure_bits: float
    total_violations: int
    keypool_min_bits: float
    keypool_mean_bits: float
    queue_total_packets: int
    aos_mean: float
    aos_max: float
    rekey_events: int


class AoSNetwork:
    def __init__(self, nodes, edges, flows, cfg: SimConfig, qkd_schedule):
        self.nodes = nodes
        self.edges = edges
        self.flows = flows
        self.cfg = cfg
        self.qkd_schedule = qkd_schedule

        # Per-flow per-node queue (FIFO of packet sizes in bits)
        self.Q: dict[tuple[str, str], deque] = {(f.name, n): deque()
                                                 for f in flows for n in nodes}
        # Per-edge key pool (bits)
        self.K: dict[tuple[str, str], float] = {
            e.key(): 0.5 * (e.k_min_bits + e.k_max_bits) for e in edges
        }
        # Per-edge generation epoch (sim seconds since last refresh)
        self.gen_epoch: dict[tuple[str, str], float] = {
            e.key(): 0.0 for e in edges
        }
        self.rng = np.random.default_rng(cfg.seed)
        self.rekey_events = 0

        # Precompute shortest-paths (for static baselines)
        self.sp_hops    = shortest_paths(nodes, edges, "hops")
        self.sp_latency = shortest_paths(nodes, edges, "latency")

        # Index edges by endpoint
        self.edge_index = {e.key(): e for e in edges}
        self.out_edges  = neighbours(edges)

        # Logging
        self.logs: list[StepLog] = []

    # -----------------------------------------------------------------
    def edge_aos(self, e: Edge, t: int) -> float:
        k = self.K[e.key()]
        u_forecast = 1e6           # 1 Mb/s forecast for the next cycle
        age = t - self.gen_epoch[e.key()]
        # depletion is the number of refresh-cycles before key reserve runs
        # out at the forecast consumption rate; clamp to a finite cap
        depletion = min(60.0, u_forecast / (k + 1e3))
        return age + self.cfg.aos_lambda * depletion

    def step(self, t: int) -> StepLog:
        cfg = self.cfg

        # ------ scenario perturbations ------
        scenario = cfg.scenario
        weather_mult = 1.0
        relay_block = set()
        if scenario == "weather":
            weather_mult = 0.2 if (t // 120) % 2 == 0 else 1.0
        elif scenario == "relay_compromise":
            if 200 <= t < 400:
                relay_block.add("GW-EU")
        elif scenario == "traffic_surge":
            pass   # handled below
        elif scenario == "coalition_partition":
            if 250 <= t < 500:
                relay_block.add("GW-APAC")

        # ------ 1. QKD key generation (per-GS rate refreshes GS-incident edges)
        for gs in [g.name for g in DEFAULT_GROUND_STATIONS]:
            rate = qkd_rate_at(t, self.qkd_schedule.get(gs, [])) * weather_mult
            if rate <= 0:
                continue
            for e in self.edges:
                if e.qkd_capable and (e.src == gs or e.dst == gs):
                    self.K[e.key()] = min(e.k_max_bits,
                                          self.K[e.key()] + rate * cfg.dt_s)
                    self.gen_epoch[e.key()] = float(t)

        # ------ 2. PQC background refresh ------
        for e in self.edges:
            if e.pqc_refresh_bps > 0:
                if cfg.scheduler == "qkd_only":
                    continue   # QKD-only refuses PQC refresh
                self.K[e.key()] = min(e.k_max_bits,
                                      self.K[e.key()]
                                      + e.pqc_refresh_bps * cfg.dt_s)

        # ------ 3. Traffic arrivals ------
        violation_count = 0
        for f in self.flows:
            arrival = f.arrival_bps * cfg.dt_s
            if scenario == "traffic_surge" and 200 <= t < 400:
                arrival *= 3.0
            self.Q[(f.name, f.src)].append(arrival)

        # ------ 4. Scheduling -------------------------------------------------
        if cfg.scheduler == "aos_ideal":
            # Per-edge per-flow max-weight backpressure: the ideal scheduler
            # of Theorem 1.  Implemented separately because it does not use
            # the per-flow shortest-path abstraction.
            r = self._step_ideal_bp(t, relay_block)
            bits_served    = r["bits_delivered"]
            rekey_events   = r["rekey_events"]
            aos_observed   = r["aos_observed"]
            violation_count += r["violations"]
            log = self._make_log(t, bits_served, violation_count,
                                 aos_observed, rekey_events)
            self.logs.append(log)
            return log

        # ------ 4 (legacy). Dijkstra-based per-flow routing ------------------
        bits_served = 0.0
        rekey_events = 0
        aos_observed: list[float] = []
        for f in self.flows:
            # Find a route per scheduler choice
            route = self._route(f, t, relay_block)
            if not route or len(route) < 2:
                continue
            # Determine pipe capacity along the route (min link cap + min key)
            pipe_cap = float("inf")
            for u, v in zip(route, route[1:]):
                e = self.edge_index.get((u, v))
                if e is None:
                    pipe_cap = 0.0
                    break
                pipe_cap = min(pipe_cap, e.capacity_bps * cfg.dt_s)
            # Key budget along the route, scaled to payload-bits served
            key_budget_bits = float("inf")
            for u, v in zip(route, route[1:]):
                e = self.edge_index.get((u, v))
                if e is None:
                    key_budget_bits = 0.0
                    break
                key_budget_bits = min(key_budget_bits, self.K[e.key()])
            key_budget = key_budget_bits / KEY_BITS_PER_PAYLOAD_BIT
            # Pop from source queue, drain through pipe
            avail = sum(self.Q[(f.name, f.src)])
            served = min(avail, pipe_cap, key_budget)
            if served < avail and avail > 0:
                # protected-bit demand exceeds key reserve -> violation
                if key_budget < pipe_cap:
                    violation_count += 1
            # Pop "served" bits from source queue (oldest first)
            remaining = served
            while remaining > 0 and self.Q[(f.name, f.src)]:
                head = self.Q[(f.name, f.src)][0]
                if head <= remaining:
                    remaining -= head
                    self.Q[(f.name, f.src)].popleft()
                else:
                    self.Q[(f.name, f.src)][0] -= remaining
                    remaining = 0
            bits_served += served
            # Consume keys along the route, scaled by KEY_BITS_PER_PAYLOAD_BIT
            key_bits_used = served * KEY_BITS_PER_PAYLOAD_BIT
            for u, v in zip(route, route[1:]):
                e = self.edge_index.get((u, v))
                if e is None: continue
                self.K[e.key()] = max(0.0, self.K[e.key()] - key_bits_used)
                # Trigger a rekey event if we crossed the policy minimum
                if self.K[e.key()] < e.k_min_bits:
                    rekey_events += 1
                aos_observed.append(self.edge_aos(e, t))

        # ------ 5. Logging ------
        log = self._make_log(t, bits_served, violation_count,
                             aos_observed, rekey_events)
        self.logs.append(log)
        return log

    def _make_log(self, t, bits_served, violation_count, aos_observed,
                  rekey_events):
        keypool_vals = list(self.K.values())
        keypool_min = min(keypool_vals)
        keypool_mean = float(np.mean(keypool_vals))
        queue_total = sum(int(round(sum(q))) for q in self.Q.values())
        return StepLog(
            t=int(t),
            total_secure_bits=float(bits_served),
            total_violations=int(violation_count),
            keypool_min_bits=float(keypool_min),
            keypool_mean_bits=float(keypool_mean),
            queue_total_packets=int(queue_total),
            aos_mean=float(np.mean(aos_observed) if aos_observed else 0.0),
            aos_max=float(max(aos_observed) if aos_observed else 0.0),
            rekey_events=int(rekey_events),
        )

    # -----------------------------------------------------------------
    def _step_ideal_bp(self, t: int, relay_block: set[str]) -> dict:
        """Per-edge per-flow max-weight backpressure (the ideal scheduler
        of Theorem 1).  Each cycle, every admissible edge picks the flow
        with the largest AoS-aware weight and serves it.  Packets that
        do not yet reach their destination accumulate at intermediate
        nodes; on subsequent cycles they continue forward by the same
        max-weight rule.
        """
        cfg = self.cfg
        bits_delivered = 0.0
        rekey_events = 0
        aos_observed: list[float] = []
        violations = 0

        # ----- Phase A. Per-edge max-weight decisions -----
        # omega weights the virtual key-queue Z in the Lyapunov function.
        # The theorem holds for any omega > 0; the chosen value sets the
        # relative emphasis on key-pool stability versus queue stability.
        # We scale it so that omega*rho*K_min ~ typical Q gradient
        # (millions of bits) and the deficit term is binding.
        rho = KEY_BITS_PER_PAYLOAD_BIT
        omega = cfg.bp_omega
        decisions: dict[tuple[str, str], tuple[str, float]] = {}
        for e in self.edges:
            if e.src in relay_block or e.dst in relay_block:
                continue
            k = self.K[e.key()]
            # virtual key queue Z = max(0, K_min - K).  Below the reserve,
            # Z is positive and discourages use through omega*rho*Z; at or
            # above the reserve, Z = 0 and the penalty vanishes.
            z = max(0.0, e.k_min_bits - k)
            aos_e = self.edge_aos(e, t)
            best_flow: str | None = None
            best_w = 0.0
            for f in self.flows:
                q_i = sum(self.Q[(f.name, e.src)])
                # Treat destination's queue as a 0-pressure sink.
                if e.dst == f.dst:
                    q_j = 0.0
                else:
                    q_j = sum(self.Q[(f.name, e.dst)])
                queue_grad = q_i - q_j
                # Lagrangian penalty matching Eq. (4) in the paper.
                penalty = (omega * rho * z
                           + cfg.bp_beta  * e.latency_ms
                           + cfg.bp_chi   * aos_e)
                w = queue_grad - penalty
                if w > best_w:
                    best_w = w
                    best_flow = f.name
            if best_flow is not None:
                decisions[e.key()] = (best_flow, best_w)

        # ----- Phase B. Serve activated edges -----
        for ekey, (fname, _w) in decisions.items():
            e = self.edge_index[ekey]
            f = next(fl for fl in self.flows if fl.name == fname)
            avail = sum(self.Q[(fname, e.src)])
            if avail <= 0:
                continue
            pipe = e.capacity_bps * cfg.dt_s
            key_budget = self.K[ekey] / rho
            served = min(avail, pipe, key_budget)
            if served <= 0:
                continue
            if served < min(avail, pipe) and key_budget < pipe:
                violations += 1
            # Drain source queue
            remaining = served
            while remaining > 0 and self.Q[(fname, e.src)]:
                head = self.Q[(fname, e.src)][0]
                if head <= remaining:
                    remaining -= head
                    self.Q[(fname, e.src)].popleft()
                else:
                    self.Q[(fname, e.src)][0] -= remaining
                    remaining = 0
            # Deliver or accumulate at next-hop queue
            if e.dst == f.dst:
                bits_delivered += served
            else:
                self.Q[(fname, e.dst)].append(served)
            # Consume keys
            key_bits_used = served * rho
            self.K[ekey] = max(0.0, self.K[ekey] - key_bits_used)
            if self.K[ekey] < e.k_min_bits:
                rekey_events += 1
            aos_observed.append(self.edge_aos(e, t))

        return dict(bits_delivered=bits_delivered,
                    rekey_events=rekey_events,
                    aos_observed=aos_observed,
                    violations=violations)

    # -----------------------------------------------------------------
    def _route(self, f: Flow, t: int, blocked: set[str]) -> list[str]:
        """Compute a route for flow f under the active scheduler.

        Every scheduler is implemented as a Dijkstra shortest-path over a
        per-edge weight function specific to that scheduler.  This keeps
        the comparison apples-to-apples: the only thing that varies
        across baselines is the edge weight.
        """
        cfg = self.cfg
        sched = cfg.scheduler

        def edge_weight(e: Edge) -> float | None:
            if e.dst in blocked or e.src in blocked:
                return None
            k = self.K[e.key()]
            if sched == "pqc_only" and e.qkd_capable and e.pqc_refresh_bps == 0:
                return None
            if sched == "qkd_only" and not e.qkd_capable:
                return None
            if k < e.k_min_bits:    # reserve constraint
                if sched in ("aos_backpressure", "key_rate_aware"):
                    # Heavy penalty rather than hard reject so a route exists
                    return 1e6 + e.latency_ms
                return None
            if sched == "shortest_path":
                return 1.0
            if sched == "max_throughput":
                return e.latency_ms
            if sched == "pqc_only":
                return e.latency_ms
            if sched == "qkd_only":
                return e.latency_ms
            if sched == "key_rate_aware":
                # Prefer high-key edges: weight inversely proportional to K
                return 1.0 + 1e6 / (k + 1.0)
            if sched == "aos_backpressure":
                # Full AoS-backpressure weight: latency + freshness + key
                # reserve gradient.  The key-reserve term mirrors the
                # `alpha * Delta K` term in the paper's backpressure
                # equation and pulls traffic away from depleted edges.
                key_term = cfg.bp_alpha * (e.k_max_bits - k)
                return (cfg.bp_beta * e.latency_ms
                        + cfg.bp_chi * self.edge_aos(e, t)
                        + key_term)
            return e.latency_ms

        # Dijkstra
        dist = {n: math.inf for n in self.nodes}
        prev = {n: None for n in self.nodes}
        dist[f.src] = 0.0
        unvisited = set(self.nodes)
        while unvisited:
            u = min(unvisited, key=lambda x: dist[x])
            if dist[u] == math.inf:
                break
            if u == f.dst:
                break
            unvisited.remove(u)
            for e in self.out_edges.get(u, []):
                if e.dst not in unvisited:
                    continue
                w = edge_weight(e)
                if w is None:
                    continue
                d = dist[u] + w
                if d < dist[e.dst]:
                    dist[e.dst] = d
                    prev[e.dst] = u
        return path(prev, f.src, f.dst)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def run(cfg: SimConfig, qkd_schedule, out_dir: Path):
    nodes, edges = default_topology()
    flows = default_flows()
    net = AoSNetwork(nodes, edges, flows, cfg, qkd_schedule)
    for t in range(0, cfg.horizon_s, cfg.dt_s):
        net.step(t)
    out_dir.mkdir(parents=True, exist_ok=True)
    fname = f"{cfg.scheduler}_{cfg.scenario}_s{cfg.seed}.csv"
    with open(out_dir / fname, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["t", "secure_bps", "violations", "k_min", "k_mean",
                         "q_total", "aos_mean", "aos_max", "rekey"])
        for log in net.logs:
            writer.writerow([log.t, log.total_secure_bits, log.total_violations,
                             log.keypool_min_bits, log.keypool_mean_bits,
                             log.queue_total_packets, log.aos_mean,
                             log.aos_max, log.rekey_events])
    # Aggregate
    bits = sum(l.total_secure_bits for l in net.logs)
    viols = sum(l.total_violations for l in net.logs)
    rekeys = sum(l.rekey_events for l in net.logs)
    qmean = float(np.mean([l.queue_total_packets for l in net.logs]))
    aosmean = float(np.mean([l.aos_mean for l in net.logs]))
    aosmax = float(np.max([l.aos_max for l in net.logs]))
    n_flow_steps = cfg.horizon_s * len(flows)
    return dict(
        scheduler=cfg.scheduler,
        scenario=cfg.scenario,
        seed=cfg.seed,
        horizon_s=cfg.horizon_s,
        secure_goodput_bps=bits / cfg.horizon_s,
        secrecy_outage_rate=viols / max(1, n_flow_steps),
        rekey_events=rekeys,
        mean_queue=qmean,
        mean_aos=aosmean,
        max_aos=aosmax,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--horizon", type=int, default=600)
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2])
    ap.add_argument("--schedulers", nargs="+",
                    default=["shortest_path", "pqc_only", "qkd_only",
                             "key_rate_aware", "aos_backpressure",
                             "aos_ideal"])
    ap.add_argument("--scenarios", nargs="+",
                    default=["nominal", "weather", "relay_compromise",
                             "traffic_surge", "coalition_partition"])
    ap.add_argument("--out", default="results")
    args = ap.parse_args()

    here = Path(__file__).resolve().parent
    out_dir = (here.parent / args.out).resolve()

    # Persist provenance once for the paper.
    here = Path(__file__).resolve().parent
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Precomputing per-seed QKD pass schedules (each pass schedule "
          "uses a different per-pass cloud-transmittance realization)")
    schedules: dict[int, dict] = {}
    provenance_str = ""
    for seed in args.seeds:
        t0 = time.time()
        sched, prov = build_qkd_schedule(start_jd=2461000.5, hours=12,
                                         weather_seed=seed)
        schedules[seed] = sched
        provenance_str = prov
        print(f"  seed {seed}: {time.time()-t0:.1f} s")
    print(f"  constellation: {provenance_str}")
    (out_dir / "provenance.txt").write_text(provenance_str + "\n")

    rows = []
    for sched in args.schedulers:
        for sc in args.scenarios:
            for seed in args.seeds:
                cfg = SimConfig(horizon_s=args.horizon, seed=seed,
                                scheduler=sched, scenario=sc)
                r = run(cfg, schedules[seed], out_dir)
                rows.append(r)
                print(f"[done] {sched:>18s}  {sc:>20s}  s={seed}  "
                      f"goodput={r['secure_goodput_bps']/1e6:.2f}Mbps  "
                      f"outage={r['secrecy_outage_rate']:.3f}  "
                      f"aos_mean={r['mean_aos']:.2f}")
    master = out_dir / "master.csv"
    with open(master, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader(); w.writerows(rows)
    print(f"\nWrote {master}")


if __name__ == "__main__":
    main()
